### ISSUE TITLE
Finish Models for Water Quality Reporting

### ISSUE THREAD

**Issue by markhildreth** [hackforwesternmass/frcog-private-wells#3]

**Comment by hjw** [comment]
Hey Mark,
The water quality models and municipality models were created in the reports dir and municipalities dir respectively by Jason.  
1. Is there a reason to choose the all in one vs separated out?
2. I looked up the way to specify legacy table names in django and am about to push that change (will put a note on the relevant issue). 

I'm hoping to get the django generated db names matching the legacy names before 8am and will then push the commit. (FYI in the Meta class for each model db_table = 'desired_name')

**Comment by markhildreth** [comment]
Ah, I didn't see those files. I'll take a look at them tonight.
